<?xml version="1.0" encoding="UTF-8"?>
<definitions name="calc"
 targetNamespace="urn:XXSystem/calc.wsdl"
 xmlns:tns="urn:XXSystem/calc.wsdl"
 xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:ns="urn:XXSystem"
 xmlns:SOAP="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:HTTP="http://schemas.xmlsoap.org/wsdl/http/"
 xmlns:MIME="http://schemas.xmlsoap.org/wsdl/mime/"
 xmlns:DIME="http://schemas.xmlsoap.org/ws/2002/04/dime/wsdl/"
 xmlns:WSDL="http://schemas.xmlsoap.org/wsdl/"
 xmlns="http://schemas.xmlsoap.org/wsdl/">

<types>

 <schema targetNamespace="urn:XXSystem"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:ns="urn:XXSystem"
  xmlns="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified"
  attributeFormDefault="unqualified">
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
 </schema>

</types>

<message name="SendAndReceiveMessageRequest">
 <part name="sendMesssage" type="xsd:string"/><!-- ns__SendAndReceiveMessage::sendMesssage -->
</message>

<message name="SendAndReceiveMessageResponse">
 <part name="recevieMessage" type="xsd:string"/><!-- ns__SendAndReceiveMessage::recevieMessage -->
</message>

<portType name="calcPortType">
 <operation name="SendAndReceiveMessage">
  <documentation>Service definition of function ns__SendAndReceiveMessage</documentation>
  <input message="tns:SendAndReceiveMessageRequest"/>
  <output message="tns:SendAndReceiveMessageResponse"/>
 </operation>
</portType>

<binding name="calc" type="tns:calcPortType">
 <SOAP:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
 <operation name="SendAndReceiveMessage">
  <SOAP:operation style="rpc" soapAction=""/>
  <input>
     <SOAP:body use="encoded" namespace="urn:XXSystem" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </input>
  <output>
     <SOAP:body use="encoded" namespace="urn:XXSystem" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </output>
 </operation>
</binding>

<service name="calc">
 <documentation>Simple calculator service</documentation>
 <port name="calc" binding="tns:calc">
  <SOAP:address location="http://localhost:80"/>
 </port>
</service>

</definitions>
